### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/kotlin-sdk#37]
```[tasklist]
### Tasks
- [ ] Publish to Maven Central during the release process
- [ ] Update readme to include updated install instructions
```

**Comment by nicklasl** [comment]
@toddbaert do you think you could assist us with this a bit?

I would assume that we want more steps in the [release-please.yaml](https://github.com/open-feature/kotlin-sdk/blob/main/.github/workflows/release_please.yaml) similar to what the [java sdk does](https://github.com/open-feature/java-sdk/blob/main/.github/workflows/release.yml#L44-L58)? But with `./gradlew publish` instead?

**Comment by toddbaert** [comment]
> I would assume that we want more steps in the [release-please.yaml](https://github.com/open-feature/kotlin-sdk/blob/main/.github/workflows/release_please.yaml) similar to what the [java sdk does](https://github.com/open-feature/java-sdk/blob/main/.github/workflows/release.yml#L44-L58)? But with `./gradlew publish` instead?

Yes - but honestly the bulk of the work is handled by maven, not the workflows. Specifically, we use the `nexus-staging-maven-plugin`... This is because (as described [here](https://central.sonatype.org/publish/publish-guide/#create-a-ticket-with-sonatype)) artifacts generally are not pushed to maven central directly. Instead, they are pushed to some other repository, and then periodically exposed through Maven Central. We use OSSRH (a Nexus instance) for this. Maven central and OSSRH have quite a few requirements about artifacts, and validate conformance as part of the staging; the `nexus-staging-maven-plugin` handles this automatically. We already have credentials for OSSRH, and we can publish any artifact under the group id `dev.openfeature`.

I think you'll have to use https://github.com/Codearte/gradle-nexus-staging-plugin or maybe https://github.com/gradle-nexus/publish-plugin/ to do something similar to what we do in the java-sdk [pom.xml](https://github.com/open-feature/java-sdk/blob/main/pom.xml#L423-L435).

**Comment by Ahwazi111** [comment]
👍
